// Asset Manifest Types
// Generated by scripts/generate-asset-manifest.js

export interface ManifestFile {
  /** File name with extension */
  name: string;
  /** Relative path from image-assets root */
  path: string;
  /** File extension without dot (e.g., 'svg', 'png') */
  extension: string;
  /** File size in bytes */
  size: number;
  /** Last modified timestamp (ISO string) */
  modified: string;
}

export interface ManifestCollection {
  /** Collection identifier (folder name) */
  name: string;
  /** Human-readable display name */
  displayName: string;
  /** Array of files in this collection */
  files: ManifestFile[];
  /** Total number of files in collection */
  count: number;
}

export interface AssetManifest {
  /** Timestamp when manifest was generated (ISO string) */
  generated: string;
  /** Map of collection name to collection data */
  collections: Record<string, ManifestCollection>;
  /** Total number of files across all collections */
  totalFiles: number;
  /** List of supported file extensions */
  supportedExtensions: string[];
}
